### ISSUE TITLE
.gemrelease doesn't work with key and host

### ISSUE THREAD

**Issue by eprothro** [svenfuchs/gem-release#59]
running `gem build` followed by `gem push --key foo --host http://foo.host/private` works.

However with a .gemrelease
```yml
release:
  key: foo
  host: http://foo.host/private
```

Running `gem release` fails, with a 401 from my gem server:

```
...
Pushing gem to http://foo.host/private...
Authorization key is invalid
...
Tasks: TOP => release => release:rubygem_push
```

Are `host` and `key` not designed to work in this manner? Documentation leads me to believe they are.
